import './globals.css'
import { Dosis } from 'next/font/google'

const inter = Dosis({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      
    </html>
  )
}
